RAID = [
    "ᗰᗩDᗩᖇᑕHOD TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗰE GHᑌTKᗩ KHᗩᗩKE THOOK DᑌNGᗩ",
    "TEᖇE ᗷEHEN K ᑕHᑌT ᗰE ᑕHᗩKᑌ Dᗩᗩᒪ Kᗩᖇ ᑕHᑌT Kᗩ KHOON Kᗩᖇ DᑌGᗩ",
    "TEᖇI ᗷᕼEᑎ NHI HᗩI KYᗩ? 9 ᗰᗩHINE ᖇᑌK SᗩGI ᗷᕼEᑎ DETᗩ Hᑌ",
    "TEᖇI ᗰᗩᗩ K ᗷHOSDE ᗰE ᗩEᖇOᑭᒪᗩNEᑭᗩᖇK KᗩᖇKE ᑌDᗩᗩN ᗷHᗩᖇ DᑌGᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗰE SᑌTᒪI ᗷOᗰᗷ ᖴOD DᑌNGᗩ TEᖇI ᗰᗩᗩ KI ᒍHᗩᗩTE ᒍᗩᒪ KE KHᗩᗩK HO ᒍᗩYEGI",
    "TEᖇI ᗰᗩᗩKI ᑕHᑌT ᗰE SᑕOOTEᖇ Dᗩᗩᒪ DᑌGᗩ",
    "TEᖇE ᗷEHEN K ᑕHᑌT ᗰE ᑕHᗩKᑌ Dᗩᗩᒪ Kᗩᖇ ᑕHᑌT Kᗩ KHOON Kᗩᖇ DᑌGᗩ",
    "TEᖇE ᗷEHEN K ᑕHᑌT ᗰE ᑕHᗩKᑌ Dᗩᗩᒪ Kᗩᖇ ᑕHᑌT Kᗩ KHOON Kᗩᖇ DᑌGᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT KᗩKTE GᗩᒪI KE KᑌTTO ᗰE ᗷᗩᗩT DᑌNGᗩ ᑭHIᖇ ᗷᖇEᗩD KI TᗩᖇH KHᗩYENGE ᗯO TEᖇI ᗰᗩᗩ KI ᑕHᑌT",
    "DᑌDH HIᒪᗩᗩᑌNGᗩ TEᖇI ᗷᕼEᑎ KE ᑌᑭᖇ NIᑕHE",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗰE HᗩTTH DᗩᒪKE ᗷᗩᑕᑕHE NIKᗩᒪ DᑌNGᗩ ",
    "TEᖇI ᗷEHN KI ᑕHᑌT ᗰE KEᒪE KE ᑕHIᒪKE",
    "TEᖇI ᗷHEN KI ᑕHᑌT ᗰE ᑌSEᖇᗷOT ᒪᗩGᗩᗩᑌNGᗩ SᗩSTE Sᑭᗩᗰ KE ᑕHODE",
    "TEᖇI ᗰᗩᗩ KE ᗷHOSDE ᗰE ᗩᑕ ᒪᗩGᗩ DᑌNGᗩ SᗩᗩᖇI GᗩᖇᗰI NIKᗩᒪ ᒍᗩᗩYEGI",
    "TEᖇI ᗷᕼEᑎ KO HOᖇᒪIᑕKS ᑭEEᒪᗩᑌNGᗩ ᗰᗩDᗩᖇᑕHOD",
    "TEᖇI ᗰᗩᗩ KI GᗩᗩND ᗰE SᗩᖇIYᗩ Dᗩᗩᒪ DᑌNGᗩ ᗰᗩDᗩᖇᑕHOD ᑌSI SᗩᖇIYE ᑭᖇ TᗩNG KE ᗷᗩᑕHE ᑭᗩIDᗩ HONGE",
    "TEᖇI ᗰᗩᗩ KO IᑎᗪOᖇE ᗯᗩᗩᒪE ᖇOOᗪ ᗷᕼᗩIYᗩ Kᗩ ᒪᑌᑎᗪ ᗰᑌᗷᗩᖇᗩK",
    "TEᖇI ᗰᑌᗰᗰY KI ᖴᗩNTᗩSY Hᑌ ᒪᗩᗯDE, Tᑌ ᗩᑭNI ᗷHEN KO SᗰᗷHᗩᗩᒪ",
    "TEᖇI ᗷᕼEᑎ KE ᗷHOSDE ᗰE XᐯIDEOS.ᑕOᗰ ᑕHᗩᒪᗩ KE ᗰᑌTH ᗰᗩᗩᖇᑌNGᗩ",
    "TEᖇI ᗰᗩᗩ Kᗩ GᖇOᑌᑭ ᗯᗩᗩᒪO KE SᗩᗩTH ᗰIᒪKE GᗩNG ᗷᗩNG KᖇᑌNGᗩ",
    "TEᖇI ITEᗰ KI GᗩᗩND ᗰE ᒪᑌND DᗩᗩᒪKE,TEᖇE ᒍᗩISᗩ EK Oᖇ NIKᗩᗩᒪ DᑌNGᗩ ᗰᗩDᗩᖇᑕHOD",
    "ᗩᑌKᗩᗩT ᗰE ᖇEH ᐯᖇNᗩ GᗩᗩND ᗰE DᗩNDᗩ Dᗩᗩᒪ KE ᗰᑌH SE NIKᗩᗩᒪ DᑌNGᗩ SHᗩᖇIᖇ ᗷHI DᗩNDE ᒍESᗩ DIKHEGᗩ",
    "TEᖇI ᗰᑌᗰᗰY KE SᗩᗩTH ᒪᑌDO KHEᒪTE KHEᒪTE ᑌSKE ᗰᑌH ᗰE ᗩᑭNᗩ ᒪODᗩ DE DᑌNGᗩ",
    "TEᖇI ᗷᕼEᑎ KO ᗩᑭNE ᒪᑌND ᑭᖇ ITNᗩ ᒍHᑌᒪᗩᗩᑌNGᗩ KI ᒍHᑌᒪTE ᒍHᑌᒪTE HI ᗷᗩᑕHᗩ ᑭᗩIDᗩ Kᖇ DEGI",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗰEI ᗷᗩTTEᖇY ᒪᗩGᗩ KE ᑭOᗯEᖇᗷᗩNK ᗷᗩNᗩ DᑌNGᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗰEI ᑕ++ STᖇING ENᑕᖇYᑭTION ᒪᗩGᗩ DᑌNGᗩ ᗷᗩHTI HᑌYI ᑕHᑌT ᖇᑌK ᒍᗩYEGI",
    "TEᖇI ᗰᗩᗩ KE GᗩᗩND ᗰEI ᒍHᗩᗩDᑌ Dᗩᒪ KE ᗰOᖇ ᗷᗩNᗩ DᑌNGᗩᗩ",
    "TEᖇI ᑕHᑌT KI ᑕHᑌT ᗰEI SHOᑌᒪDEᖇING Kᗩᖇ DᑌNGᗩᗩ HIᒪᗩTE HᑌYE ᗷHI DᗩᖇD HOGᗩᗩᗩ",
    "TEᖇI ᗰᗩᗩ KO ᖇEDI ᑭE ᗷᗩITHᗩᒪ KE ᑌSSE ᑌSKI ᑕHᑌT ᗷIᒪᗯᗩᑌNGᗩᗩ",
    "ᗷHOSDIKE TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗰEI 4 HOᒪE HᗩI ᑌNᗰE ᗰSEᗩᒪ ᒪᗩGᗩ ᗷᗩHᑌT ᗷᗩHETI HᗩI ᗷHOᖴDIKE",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗰEI SᑌDO ᒪᗩGᗩ KE ᗷIGSᑭᗩᗰ ᒪᗩGᗩ KE 9999 ᖴᑌᑕK ᒪᗩGᗩᗩ Dᑌ",
    "TEᖇI ᐯᗩHEN KE ᗷHOSDIKE ᗰEI ᗷESᗩN KE ᒪᗩDDᑌ ᗷHᗩᖇ DᑌNGᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT KHOD KE ᑌSᗰE ᑕYᒪINDEᖇ ᖴIT KᗩᖇKE ᑌSᗰEE Dᗩᒪ ᗰᗩKHᗩNI ᗷᗩNᗩᑌNGᗩᗩᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗰEI SHEESHᗩ Dᗩᒪ DᑌNGᗩᗩᗩ ᗩᑌᖇ ᑕHᗩᑌᖇᗩHE ᑭE TᗩᗩNG DᑌNGᗩ ᗷHOSDIKE",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗰEI ᑕᖇEDIT ᑕᗩᖇD Dᗩᒪ KE ᗩGE SE 500 KE KᗩᗩᖇE KᗩᗩᖇE NOTE NIKᗩᒪᑌNGᗩᗩ ᗷHOSDIKE",
    "TEᖇI ᗰᗩᗩ KE SᗩTH Sᑌᗩᖇ Kᗩ SEX Kᗩᖇᗯᗩ DᑌNGᗩᗩ EK SᗩTH 6-6 ᗷᗩᑕHE DEGI",
    "TEᖇI ᗷᗩHEN KI ᑕHᑌT ᗰEI ᗩᑭᑭᒪE Kᗩ 18ᗯ ᗯᗩᒪᗩ ᑕHᗩᖇGEᖇ",
    "TEᖇI ᗷᗩHEN KI GᗩᗩND ᗰEI ONEᑭᒪᑌS Kᗩ ᗯᖇᗩᑭ ᑕHᗩᖇGEᖇ 30ᗯ HIGH ᑭOᗯEᖇ",
    "TEᖇI ᗷᗩHEN KI ᑕHᑌT KO ᗩᗰᗩᘔON SE OᖇDEᖇ KᗩᖇᑌNGᗩ 10 ᖇs ᗰEI ᗩᑌᖇ ᖴᒪIᑭKᗩᖇT ᑭE 20 ᖇS ᗰEI ᗷEᑕH DᑌNGᗩ",
    "TEᖇI ᗰᗩᗩ KI ᗷᗩDI ᗷHᑌND ᗰE ᘔOᗰᗩTO Dᗩᒪ KE SᑌᗷᗯᗩY Kᗩ ᗷᖴᖴ ᐯEG Sᑌᗷ ᑕOᗰᗷO [15ᑕᗰ , 16 inᑕhes ] OᖇDEᖇ ᑕOD KᖇᐯᗩᑌNGᗩ Oᖇ TEᖇI ᗰᗩᗩ ᒍᗩᗷ DIᒪIᐯEᖇY DENE ᗩYEGI Tᗩᗷ ᑌSᑭE ᒍᗩᗩDᑌ KᖇᑌNGᗩ Oᖇ ᖴIᖇ 9 ᗰONTH ᗷᗩᗩD ᐯO EK Oᖇ ᖴᖇEE DIᒪIᐯEᖇY DEGI",
    "TEᖇI ᗷHEN KI KᗩᒪᒪI ᑕHᑌT KO ᑕHOD ᑕHOD Kᖇ ᒪᗩᗩᒪ Kᖇᑌᑌ",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗰE ᑕHᗩNGES ᑕOᗰᗰIT KᖇᑌGᗩ ᖴIᖇ TEᖇI ᗷHEEN KI ᑕHᑌT ᗩᑌTOᗰᗩTIᑕᗩᒪᒪY ᑌᑭDᗩTE HOᒍᗩᗩYEGI",
    "TEᖇI ᗰᗩᑌSI KE ᗷHOSDE ᗰEI INDIᗩN ᖇᗩIᒪᗯᗩY ᗯᗩᒪO Kᗩ ᒪODᗩᗩᗩ",
    "Tᑌ TEᖇI ᗷᗩHEN TEᖇᗩ KHᗩNDᗩN Sᗩᗷ ᗷᗩHEN KE ᒪᗩᗯDE ᖇᗩNDI HᗩI ᖇᗩNDI",
    "TEᖇI ᗷᗩHEN KI ᑕHᑌT ᗰEI IONIᑕ ᗷOND ᗷᗩNᗩ KE ᐯIᖇGINITY ᒪOOSE Kᗩᖇᗯᗩ DᑌNGᗩ ᑌSKI",
    "TEᖇI ᖇᗩNDI ᗰᗩᗩ SE ᑭᑌᑕHNᗩ ᗷᗩᗩᑭ Kᗩ Nᗩᗩᗰ ᗷᗩHEN KE ᒪODE",
    "Tᑌ ᗩᑌᖇ TEᖇI ᗰᗩᗩ DONO KI ᗷHOSDE ᗰEI ᗰETᖇO ᑕHᗩᒪᗯᗩ DᑌNGᗩ ᗰᗩDᗩᖇXHOD",
    "TEᖇI ᗰᗩᗩ KO ITNᗩ ᑕHODᑌNGᗩ TEᖇᗩ ᗷᗩᗩᑭ ᗷHI ᑌSKO ᑭᗩHᑕHᗩNᗩNE SE ᗰᗩNᗩ Kᗩᖇ DEGᗩ",
    "TEᖇI ᗷᗩHEN KE ᗷHOSDE ᗰEI HᗩIᖇ DᖇYEᖇ ᑕHᗩᒪᗩ DᑌNGᗩᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗰEI TEᒪEGᖇᗩᗰ KI SᗩᖇI ᖇᗩNDIYON Kᗩ ᖇᗩNDI KHᗩNᗩ KHOᒪ DᑌNGᗩᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗩᒪEXᗩ Dᗩᒪ KEE Dᒍ ᗷᗩᒍᗩᑌNGᗩᗩᗩ",
    "TEᖇI ᗰᗩᗩ KE ᗷHOSDE ᗰEI GITHᑌᗷ Dᗩᒪ KE ᗩᑭNᗩ ᗷOT HOST KᗩᖇᑌNGᗩᗩ",
    "TEᖇI ᗷᗩHEN Kᗩ ᐯᑭS ᗷᗩNᗩ KE 24*7 ᗷᗩSH ᑕHᑌDᗩI ᑕOᗰᗰᗩND DE DᑌNGᗩᗩ",
    "TEᖇI ᗰᑌᗰᗰY KI ᑕHᑌT ᗰEI TEᖇE ᒪᗩND KO Dᗩᒪ KE KᗩᗩT DᑌNGᗩ ᗰᗩDᗩᖇᑕHOD",
    "SᑌN TEᖇI ᗰᗩᗩ Kᗩ ᗷHOSDᗩ ᗩᑌᖇ TEᖇI ᗷᗩHEN Kᗩ ᗷHI ᗷHOSDᗩ",
    "TᑌᒍHE DEKH KE TEᖇI ᖇᗩNDI ᗷᗩHEN ᑭE TᗩᖇᗩS ᗩTᗩ HᗩI ᗰᑌᒍHE ᗷᗩHEN KE ᒪODEEEE",
    "SᑌN ᗰᗩDᗩᖇᑕHOD ᒍYᗩDᗩ Nᗩ ᑌᑕHᗩᒪ ᗰᗩᗩ ᑕHOD DENGE EK ᗰIN ᗰEI",
    "ᗩᑭNI ᗩᗰᗰᗩ SE ᑭᑌᑕHNᗩ ᑌSKO ᑌS KᗩᗩᒪI ᖇᗩᗩT ᗰEI KᗩᑌN ᑕHODNEE ᗩYᗩ THᗩᗩᗩ! TEᖇE IS ᑭᗩᑭᗩ Kᗩ Nᗩᗩᗰ ᒪEGI",
    "TOHᗩᖇ ᗷᗩHIN ᑕHODᑌ ᗷᗷᗩHEN KE ᒪᗩᗯDE ᑌSᗰE ᗰITTI Dᗩᒪ KE ᑕEᗰENT SE ᗷHᗩᖇ Dᑌ",
    "TᑌᒍHE ᗩᗷ TᗩK NᗩHI SᗰᒍH ᗩYᗩ KI ᗰᗩI HI Hᑌ TᑌᒍHE ᑭᗩIDᗩ KᗩᖇNE ᗯᗩᒪᗩ ᗷHOSDIKEE ᗩᑭNI ᗰᗩᗩ SE ᑭᑌᑕH ᖇᗩNDI KE ᗷᗩᑕHEEEE",
    "TEᖇI ᗰᗩᗩ KE ᗷHOSDE ᗰEI SᑭOTIᖴY Dᗩᒪ KE ᒪOᖴI ᗷᗩᒍᗩᑌNGᗩ DIN ᗷHᗩᖇ",
    "TEᖇI ᗰᗩᗩ Kᗩ NᗩYᗩ ᖇᗩNDI KHᗩNᗩ KHOᒪᑌNGᗩ ᑕHINTᗩ ᗰᗩT Kᗩᖇ",
    "TEᖇᗩ ᗷᗩᗩᑭ Hᑌ ᗷHOSDIKE TEᖇI ᗰᗩᗩ KO ᖇᗩNDI KHᗩNE ᑭE ᑕHᑌDᗯᗩ KE ᑌS ᑭᗩISE KI Dᗩᗩᖇᑌ ᑭEETᗩ Hᑌ",
    "TEᖇI ᗷᗩHEN KI ᑕHᑌT ᗰEI ᗩᑭNᗩ ᗷᗩDᗩ Sᗩ ᒪODᗩ GHᑌSSᗩ DᑌNGᗩᗩ Kᗩᒪᒪᗩᗩᑭ KE ᗰᗩᖇ ᒍᗩYEGI",
    "TOHᗩᖇ ᗰᑌᗰᗰY KI ᑕHᑌT ᗰEI ᑭᑌᖇI KI ᑭᑌᖇI KINGᖴISHEᖇ KI ᗷOTTᒪE Dᗩᒪ KE TOD DᑌNGᗩ ᗩNDEᖇ HI",
    "TEᖇI ᗰᗩᗩ KO ITNᗩ ᑕHODᑌNGᗩ KI SᗩᑭNE ᗰEI ᗷHI ᗰEᖇI ᑕHᑌDᗩI YᗩᗩD KᗩᖇEGI ᖇᗩNDI",
    "TEᖇI ᗰᑌᗰᗰY ᗩᑌᖇ ᗷᗩHEN KO DᗩᑌDᗩ DᗩᑌDᗩ NE ᑕHODᑌNGᗩ ᑌNKE NO ᗷOᒪNE ᑭE ᗷHI ᒪᗩND GHᑌSᗩ DᑌNGᗩ ᗩNDEᖇ TᗩK",
    "TEᖇI ᗰᑌᗰᗰY KI ᑕHᑌT KO ONᒪINE OᒪX ᑭE ᗷEᑕHᑌNGᗩ ᗩᑌᖇ ᑭᗩISE SE TEᖇI ᗷᗩHEN Kᗩ KOTHᗩ KHOᒪ DᑌNGᗩ",
    "TEᖇI ᗰᗩᗩ KE ᗷHOSDᗩ ITNᗩ ᑕHODᑌNGᗩ KI Tᑌ ᑕᗩH KE ᗷHI ᗯO ᗰᗩST ᑕHᑌDᗩI SE Dᑌᖇ NHI ᒍᗩ ᑭᗩYEGᗩᗩ",
    "SᑌN ᗷE ᖇᗩNDI KI ᗩᑌᒪᗩᗩD Tᑌ ᗩᑭNI ᗷᗩHEN SE SEEKH KᑌᑕH KᗩISE GᗩᗩND ᗰᗩᖇᗯᗩTE HᗩI",
    "TEᖇI ᗰᗩᗩ Kᗩ Yᗩᗩᖇ Hᑌ ᗰEI ᗩᑌᖇ TEᖇI ᗷᗩHEN Kᗩ ᑭYᗩᗩᖇ Hᑌ ᗰEI ᗩᒍᗩ ᗰEᖇᗩ ᒪᗩND ᑕHOOS ᒪE",
    "TEᖇI ᗷHEN KI ᑕHᑌT ᗰE ᑌSEᖇᗷOT ᒪᗩGᗩᗩᑌNGᗩ SᗩSTE Sᑭᗩᗰ KE ᑕHODE",
    "TEᖇI ᗰᗩᗩ KI GᗩᗩND ᗰE SᗩᖇIYᗩ Dᗩᗩᒪ DᑌNGᗩ ᗰᗩDᗩᖇᑕHOD ᑌSI SᗩᖇIYE ᑭᖇ TᗩNG KE ᗷᗩᑕHE ᑭᗩIDᗩ HONGE",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗰE HᗩTTH DᗩᒪKE ᗷᗩᑕᑕHE NIKᗩᒪ DᑌNGᗩ",
    "TEᖇI ᗷEHN KI ᑕHᑌT ᗰE KEᒪE KE ᑕHIᒪKE",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᗰE SᑌTᒪI ᗷOᗰᗷ ᖴOD DᑌNGᗩ TEᖇI ᗰᗩᗩ KI ᒍHᗩᗩTE ᒍᗩᒪ KE KHᗩᗩK HO ᒍᗩYEGI",
    "TEᖇI ᗷᕼEᑎ KO HOᖇᒪIᑕKS ᑭEEᒪᗩKE ᑕHODᑌNGᗩ ᗰᗩDᗩᖇᑕHOD",
    "TEᖇI ITEᗰ KI GᗩᗩND ᗰE ᒪᑌND DᗩᗩᒪKE,TEᖇE ᒍᗩISᗩ EK Oᖇ NIKᗩᗩᒪ DᑌNGᗩ ᗰᗩDᗩᖇᑕHOD",
    "TEᖇI ᗷᕼEᑎ KO ᗩᑭNE ᒪᑌND ᑭᖇ ITNᗩ ᒍHᑌᒪᗩᗩᑌNGᗩ KI ᒍHᑌᒪTE ᒍHᑌᒪTE HI ᗷᗩᑕHᗩ ᑭᗩIDᗩ Kᖇ DEGI",
    "Sᑌᗩᖇ KE ᑭIᒪᒪE TEᖇI ᗰᗩᗩKO SᗩDᗩK ᑭᖇ ᒪITᗩKE ᑕHOD DᑌNGᗩ",
    "ᗩᗷE TEᖇI ᗰᗩᗩKᗩ ᗷHOSDᗩ ᗰᗩDEᖇᑕHOOD Kᖇ ᑭIᒪᒪE ᑭᗩᑭᗩ SE ᒪᗩDEGᗩ Tᑌ",
    "GᗩᒪI GᗩᒪI NE SHOᖇ HE TEᖇI ᗰᗩᗩ ᖇᗩNDI ᑕHOᖇ HE",
    "ᗩᗷE TEᖇI ᗷEHEN KO ᑕHODᑌ ᖇᗩNDIKE ᑭIᒪᒪE KᑌTTE KE ᑕHODE",
    "TEᖇI ᗰᗩᗩKO ᗩISE ᑕHODᗩ ᗩISE ᑕHODᗩ TEᖇI ᗰᗩᗩᗩ ᗷED ᑭEHI ᗰᑌTH DIᗩ",
    "TEᖇI ᗷEHEN KE ᗷHOSDE ᗰE ᗩᗩᗩG ᒪᗩGᗩDIᗩ ᗰEᖇᗩ ᗰOTᗩ ᒪᑌND DᗩᒪKE",
    "ᖇᗩNDIKE ᗷᗩᑕHHE TEᖇI ᗰᗩᗩKO ᑕHODᑌ ᑕHᗩᒪ NIKᗩᒪ",
    "KITNᗩ ᑕHODᑌ TEᖇI ᖇᗩNDI ᗰᗩᗩKI ᑕHᑌTH ᗩᗷᗷ ᗩᑭNI ᗷEHEN KO ᗷHEᒍ",
    "TEᖇI ᗷEHEN KOTO ᑕHOD ᑕHODKE ᑭᑌᖇᗩ ᖴᗩᗩD DIᗩ ᑕHᑌTH ᗩᗷᗷ TEᖇI Gᖴ KO ᗷHEᒍ",
    "TEᖇI Gᖴ KO ETNᗩ ᑕHODᗩ ᗷEHEN KE ᒪODE TEᖇI Gᖴ TO ᗰEᖇI ᖇᗩNDI ᗷᗩNGᗩYI ᗩᗷᗷ ᑕHᗩᒪ TEᖇI ᗰᗩᗩKO ᑕHODTᗩ ᖴIᖇSE",
    "HᗩᖇI HᗩᖇI GHᗩᗩS ᗰE ᒍHOᑭDᗩ TEᖇI ᗰᗩᗩKᗩ ᗷHOSDᗩ",
    "ᑕHᗩᒪ TEᖇE ᗷᗩᗩᑭ KO ᗷHEᒍ TEᖇᗩ ᗷᗩSKᗩ NHI HE ᑭᗩᑭᗩ SE ᒪᗩDEGᗩ Tᑌ",
    "TEᖇI ᗷEHEN KI ᑕHᑌTH ᗰE ᗷOᗰᗷ DᗩᒪKE ᑌDᗩ DᑌNGᗩ ᗰᗩᗩKE ᒪᗩᗯDE",
    "TEᖇI ᗰᗩᗩKO TᖇᗩIN ᗰE ᒪEᒍᗩKE TOᑭ ᗷED ᑭE ᒪITᗩKE ᑕHOD DᑌNGᗩ Sᑌᗩᖇ KE ᑭIᒪᒪE",
    "TEᖇI ᗰᗩᗩᗩKE NᑌDES GOOGᒪE ᑭE ᑌᑭᒪOᗩD KᗩᖇDᑌNGᗩ ᗷEHEN KE ᒪᗩEᗯDE",
    "TEᖇI ᗷEHEN KO ᑕHOD ᑕHODKE ᐯIDEO ᗷᗩNᗩKE XNXX.ᑕOᗰ ᑭE NEEᒪᗩᗰ KᗩᖇDᑌNGᗩ KᑌTTE KE ᑭIᒪᒪE",
    "TEᖇI ᗰᗩᗩᗩKI ᑕHᑌDᗩI KO ᑭOᖇNHᑌᗷ.ᑕOᗰ ᑭE ᑌᑭᒪOᗩD KᗩᖇDᑌNGᗩ Sᑌᗩᖇ KE ᑕHODE",
    "ᗩᗷE TEᖇI ᗷEHEN KO ᑕHODᑌ ᖇᗩNDIKE ᗷᗩᑕHHE TEᖇEKO ᑕHᗩKKO SE ᑭIᒪᗯᗩᐯᑌNGᗩ ᖇᗩNDIKE ᗷᗩᑕHHE",
    "TEᖇI ᗰᗩᗩKI ᑕHᑌTH ᖴᗩᗩDKE ᖇᗩKDIᗩ ᗰᗩᗩKE ᒪODE ᒍᗩᗩ ᗩᗷᗷ SIᒪᗯᗩᒪE",
    "TEᖇI ᗷEHEN KI ᑕHᑌTH ᗰE ᗰEᖇᗩ ᒪᑌND Kᗩᗩᒪᗩ",
    "TEᖇI ᗷEHEN ᒪETI ᗰEᖇI ᒪᑌND ᗷᗩDE ᗰᗩSTI SE TEᖇI ᗷEHEN KO ᗰENE ᑕHOD Dᗩᒪᗩ ᗷOHOT SᗩSTE SE",
    "ᗷETE Tᑌ ᗷᗩᗩᑭ SE ᒪEGᗩ ᑭᗩNGᗩ TEᖇI ᗰᗩᗩᗩ KO ᑕHOD DᑌNGᗩ KᗩᖇKE NᗩNGᗩ",
    "HᗩHᗩHᗩH ᗰEᖇE ᗷETE ᗩGᒪI ᗷᗩᗩᖇ ᗩᑭNI ᗰᗩᗩKO ᒪEKE ᗩᗩYᗩ ᗰᗩTH KᗩT Oᖇ ᗰEᖇE ᗰOTE ᒪᑌND SE ᑕHᑌDᗯᗩYᗩ ᗰᗩTH Kᗩᖇ",
    "ᑕHᗩᒪ ᗷETᗩ TᑌᒍHE ᗰᗩᗩᖴ KIᗩ ᗩᗷᗷ ᗩᑭNI Gᖴ KO ᗷHEᒍ",
    "SHᗩᖇᗩᗰ Kᗩᖇ TEᖇI ᗷEHEN Kᗩ ᗷHOSDᗩ KITNᗩ GᗩᗩᒪIᗩ SᑌNᗯᗩYEGᗩ ᗩᑭNI ᗰᗩᗩᗩ ᗷEHEN KE ᑌᑭEᖇ",
    "ᗩᗷE ᖇᗩNDIKE ᗷᗩᑕHHE ᗩᑌKᗩT NHI HETO ᗩᑭNI ᖇᗩNDI ᗰᗩᗩKO ᒪEKE ᗩᗩYᗩ ᗰᗩTH Kᗩᖇ HᗩHᗩHᗩHᗩ",
    "KIDᘔ ᗰᗩDᗩᖇᑕHOD TEᖇI ᗰᗩᗩKO ᑕHOD ᑕHODKE TEᖇᖇ ᒪIYE ᗷHᗩI DEDIYᗩ",
    "ᒍᑌNGᒪE ᗰE NᗩᑕHTᗩ HE ᗰOᖇE TEᖇI ᗰᗩᗩKI ᑕHᑌDᗩI DEKKE Sᗩᗷ ᗷOᒪTE ONᑕE ᗰOᖇE ONᑕE ᗰOᖇE",
    "GᗩᒪI GᗩᒪI ᗰE ᖇEHTᗩ HE SᗩND TEᖇI ᗰᗩᗩKO ᑕHOD Dᗩᒪᗩ Oᖇ ᗷᗩNᗩ DIᗩ ᖇᗩND",
    "Sᗩᗷ ᗷOᒪTE ᗰᑌᒍHKO ᑭᗩᑭᗩ KYOᑌNKI ᗰENE ᗷᗩNᗩDIᗩ TEᖇI ᗰᗩᗩKO ᑭᖇEGNENT",
    "Sᑌᗩᖇ KE ᑭIᒪᒪE TEᖇI ᗰᗩᗩKI ᑕHᑌTH ᗰE Sᑌᗩᖇ Kᗩ ᒪOᑌDᗩ Oᖇ TEᖇI ᗷEHEN KI ᑕHᑌTH ᗰE ᗰEᖇᗩ ᒪODᗩ",
    "ᑕHᗩᒪ ᑕHᗩᒪ ᗩᑭNI ᗰᗩᗩKI ᑕHᑌᑕHIYᗩ DIKᗩ",
    "HᗩHᗩHᗩHᗩ ᗷᗩᑕHHE TEᖇI ᗰᗩᗩᗩKO ᑕHOD DIᗩ NᗩNGᗩ KᗩᖇKE",
    "TEᖇI Gᖴ HE ᗷᗩDI SEXY ᑌSKO ᑭIᒪᗩKE ᑕHOODENGE ᑭEᑭSI",
    "2 ᖇᑌᑭᗩY KI ᑭEᑭSI TEᖇI ᗰᑌᗰᗰY SᗩᗷSE SEXY ᑕHODᑌ ᑌSKO IN TᗩXI",
    "TEᖇI ᗰᗩᗩKO ᑕHEEᗰS SE ᑕHᑌDᗯᗩᐯᑌNGᗩ ᗰᗩDEᖇᑕHOOD KE ᑭIᒪᒪE",
    "TEᖇI ᗷEHEN KI ᑕHᑌTH ᗰE ᗰᑌTHKE ᖴᗩᖇᗩᖇ HOᒍᗩᐯᑌNGᗩ HᑌI HᑌI HᑌI",
    "SᑭEED ᒪᗩᗩᗩ TEᖇI ᗷEHEN ᑕHODᑌ ᖇᗩNDIKE ᑭIᒪᒪE",
    "ᗩᖇE ᖇE ᗰEᖇE ᗷETE KYOᑌN SᑭEED ᑭᗩKᗩD Nᗩ ᑭᗩᗩᗩ ᖇᗩHᗩ ᗩᑭNE ᗷᗩᗩᑭ Kᗩ HᗩHᗩH",
    "SᑌN SᑌN Sᑌᗩᖇ KE ᑭIᒪᒪE ᒍHᗩNTO KE SOᑌDᗩGᗩᖇ ᗩᑭNI ᗰᑌᗰᗰY KI NᑌDES ᗷHEᒍ",
    "ᗩᗷE SᑌN ᒪODE TEᖇI ᗷEHEN Kᗩ ᗷHOSDᗩ ᖴᗩᗩD DᑌNGᗩ",
    "TEᖇI ᗰᗩᗩKO KHᑌᒪE ᗷᗩᒍᗩᖇ ᗰE ᑕHOD Dᗩᒪᗩ Kᗩᒪ ᗰE",
]


RRAID = [
    "ᗰᗩDᗩᖇᑕHOD ᑕHIᑭKᗩᒪI KE ᒍHᗩᗩTOO KE ᗷᗩᗩᒪᒪ TEᖇI ᗰᗩᗩ KE ᗷHOSDE SE ᗷᗩᗩDE ᗰEᖇE HᗩTTO KE ᗷᗩᗩᒪ HᗩI",
    "ᗷHOSDIKe TEᖇI ᗰᗩᗩ ᑕHOD Dᗩᗩᒪᗩ Kᗩᒪ ᖇᗩᗩT ᑭᑌNᒍᗩᗷII. TEᖇI ᗰᗩᗩIYᗩ KI ᗷHOSDI ᖴᗩᗩT GᗩI ᗷᗩᒪᗩKK ᗷᗩᗩᑭ SE ᒪᗩDEGᗩᗩ",
    "ᒪᗩᗩᗩᗯEEE KE ᗷᗩᗩᗩᗩᗩᒪ TEᖇI ᗰᗩᗩ KI ᗩGE SE ᒍᗩᗩDᗩ ᗰEᖇE ᒍHᗩTOO KE ᗷᗩᗩᒪ HᗩII",
    "TEᖇI ᗰᗩ KI ᑕHᑌT ᗰE TEᖇᗩ ᒪODᗩ Dᗩᗩᒪ Kᖇ KᗩᗩT KᗩᗩTᑌ",
    "ᗰᗩᑕHᗩᖇ KI ᒍHᗩᗩT KE ᗷᗩᗩᗩᒪᒪᒪᒪ ᗩᑌKᗩTᒪESS TᗩTTE. ᗩᑌKᗩT ᗷᗩNᗩᗩ ᗷᗩᗩᑭ SE ᒪᗩDNEKI",
    "TEᖇI ᗰᗩᗩ KO Tᗩᑭᗩ Tᗩᑭ ᑕHODᗩᗩ ᖇOOD ᗷHEN KE ᒪODEE Kᗩᒪᗩᑭ TEᖇII ᗰᗩᗩ ᑕHᑌD GᗩI",
    "TEᖇI ᗰᗩ Kᗩ ᗷHOSDᗩᗩ ᗰᗩᗩᖇᑌ ᗷᗩᒪᗩKK TEᖇE ᑭᗩᖇIᗯᗩᗩᖇ KI ᗰᗩᗩ KI GᗩND ᗰE ᒪODᗩᗩ ᗰEᖇᗩᗩ",
    "TEᖇI ᗷHEN KI ᗷHOSDI 7INᑕH KIᗷKᗩᖇᑌNGᗩ ᗰE HᗩHᗩHᗩᗩ. TEᖇI ᗰᗩIYᗩ Kᗩ ᖇᗩᑭ KIYᗩ TᗩH TEᖇI ᗷHEN Kᗩ ᗷHI KᖇDᑌ",
    "TEᖇE GᗩNDᑌ ᗷᗩᗩᑭ KO ᗷEEᒍ TEᖇI ᗩᑌKᗩT NᗩHI ᗰᑌᒍSE ᒪᗩDNEKI. ᑕHᗩKKE TEEI ᗰᗩᗩ ᑕHᑌDGᗩᑌI",
    "TEᖇᗩ ᗷᗩᗩᑭ ᑕHKᗩᗩᗩᗩ + ᗰᗩᗩ ᑕHᑌDᗯᗩTᗩ ᖇING ᖇOᗩD ᑭᖇ",
    "KITNI ᑕHODᑌ TEᖇI ᗰᗩ ᗩᗷ Oᖇ Kᗩᒪ ᖇᗩᗩT ᑭᗩTᗩK ᑭᗩTᗩK Kᖇ ᑕHODᗩ TOH TᗩᗩH ᑕHᗩᒪ EK ᗩᑌᖇ ᗷᗩᗩᖇ ᑕHOD DEETᗩ Hᑌ",
    "TEᖇI ᗰᗩ KE SᗩTH ᖇEEᒪS ᗷNEGᗩ ᖇOᗩD ᑭEE ᑕHODᑌNGᗩ ITNᗩ TEᖇI ᗰᗩᗩ KO ᗰᑌTHNE NI DᑌNG",
    "ᗰᗩᒪᑌᗰ Nᗩ ᑭHᖇ KESE ᒪETᗩ Hᑌ ᗰ TEᖇI ᗰᗩ KI ᑕHᑌT Tᗩᑭᗩ Tᗩᑭᑭᑭᑭᑭ",
    "TEEI ᗰᗩᗩ KE SᗩTH ᒪOG THᖇEESOᗰE KᖇTE HᗩI ᗷHEN KE ᒪODE YE HᗩI TEᖇI ᗩᑌKᗩT",
    "SᑭEED ᑭᗩKᗩDD ᒪOᗯDEEE TEᖇI ᗰᗩS KI ᑕᑌTE SI ᑕHᑌT ᑭᖇ ᗰEᖇE NᗩᗰE Kᗩ STIᑕKEᖇ ᒪᗩGᗩᑌᑌ",
    "ᗷᗩᗩᑭ KI SᑭEED ᗰᗩTᑕH Kᖇᖇᖇ ᖇᗩᗩND KE ᑭIᒪEEE ᗩᗩᒍᗩ ᒪᗩᗩD ᗰEᖇESE",
    "HᗩHᗩHᗩHHᗩHᗩHᗩ",
    "ᑭᗩᑭᗩ KI SᑭEED ᗰTᑕH NHI HO ᖇHI KYᗩ",
    "ᗩᒪE ᗩᒪE TEᖇI ᗰᗩᗩ ᑕHOOD GᗩI KYᗩᗩ ᗰEᖇE HᗩᗩTOO ᗷEETI ᑕHᑌDGᗩII Tᑌ ",
    "ᑕHᑌD GYᗩ ᑭᗩᑭᗩ SEEE ᗷEETI ᗰᑌᒍE ᗩᗩᑕHᗩ NI ᒪᗩGTᗩ Tᑌᗰ KO ᑕHODNE ᗰEᑭᖇ Tᑌᗰ SᗩSTI ᖇᗩᗩND HO 10₹ ᗯᗩLI TᑌᗰHᗩᖇI ᑕHᑌDᗩII ISS ᒪIYE KᖇTᗩHᑌ",
    "ᗰᗩᗩᒍDᑌᖇ KO KHODNᗩ ᗩᑌᖇ ᗷᗩᗩᑭ KO ᑕHODNᗩ NᗩHI SIKHᗩTEE",
    "SᗩᒪE TEᖇI ᗰᗩᗩ Kᗩ ᗷᗩᒪᗩTT Kᗩᗩᖇ Kᖇ DIYᗩ Hᑌᗩ ᒍISS TᗩᖇIKE SE DᗩNGEᖇOᑌS ᑕHᗩKKO Kᗩ KIYᗩ TᗩHH",
    "KIDSSSS TᑌᗰHᗩᖇI ᗩᗰᗰI KI ᑕHᑌT ᑭᖇ ᗰEᖇᗩ NᗩᗰEE ᒍᗩᗩ Kᖇ DEKH TEᖇI ᗰᗩᗩ ONᒪYᖴᗩNS KI ᖇᗩNND HᗩI",
    "YE ᒪᗩDNGE ᗷᗩᑭᑭ SE INKI ᗰᗩᗩ ᑕHOD Dᗩᗩᗩᒪᗩ ᗰE ᗷᗩᗩᑭ SE ᗷᗩKᑕHODI KᗩᖇENGE",
    "ᗷHEN KE ᒪODEEE KIDSSS ᖴᗩᖇᗩᖇ ᗰᗩᗩ ᑕHOD Dᗩᗩᒪᗩᗩᗩ ᖇOOD INKII ",
    "ᗷHEN KE ᒪOᗯDE SHᗩᖇᗩᗰᗰ Kᖇᖇ TEᖇI ᗰᗩᗩ ᑕHᑌD GᗩI ISS GᖇOᑌᑭ ᑭᖇ ᗷINᗩ ᖇᑌKHEE ",
    "NᗩᒪᒪEE TEᖇI ᗰᗩᗩ KO ᗷIᑕH ᖇOᗩD ᑭᖇ NᗩNGᗩᗩ KᖇKEᑕHODᑌNGᗩᗩ ᗷINᗩᗩ ᖇᑌKHE",
    "Sᑌᗩᖇ KE ᑭIᒪᒪE TEᖇI ᗰᗩᗩKO SᗩDᗩK ᑭᖇ ᒪITᗩKE ᑕHOD DᑌNGᗩ",
    "ᗩᗷE TEᖇI ᗰᗩᗩKᗩ ᗷHOSDᗩ ᗰᗩDEᖇᑕHOOD Kᖇ ᑭIᒪᒪE ᑭᗩᑭᗩ SE ᒪᗩDEGᗩ Tᑌ",
    "ᗩᗷE TEᖇI ᗷEHEN KO ᑕHODᑌ ᖇᗩNDIKE ᑭIᒪᒪE KᑌTTE KE ᑕHODE",
    "TEᖇI ᗰᗩᗩKO ᗩISE ᑕHODᗩ ᗩISE ᑕHODᗩ TEᖇI ᗰᗩᗩᗩ ᗷED ᑭEHI ᗰᑌTH DIᗩ",
    "TEᖇI ᗷEHEN KE ᗷHOSDE ᗰE ᗩᗩᗩG ᒪᗩGᗩDIᗩ ᗰEᖇᗩ ᗰOTᗩ ᒪᑌND DᗩᒪKE",
    "ᖇᗩNDIKE ᗷᗩᑕHHE TEᖇI ᗰᗩᗩKO ᑕHODᑌ ᑕHᗩᒪ NIKᗩᒪ TEᖇI ᗰᗩᗩ ᑕHᑌD GᗩI ᗩᑌᖇ ᖴᗩᗩᖇᗩᖇ HO GᗩI",
    "KITNᗩ ᑕHODᑌ TEᖇI ᖇᗩNDI ᗰᗩᗩKI ᑕHᑌTH ᗩᗷᗷ ᗩᑭNI ᗷEHEN KO ᗷHEᒍ",
    "TEᖇI ᗷEHEN KOTO ᑕHOD ᑕHODKE ᑭᑌᖇᗩ ᖴᗩᗩD DIᗩ ᑕHᑌTH ᗩᗷᗷ TEᖇI Gᖴ KO ᗷHEᒍ",
    "TEᖇI Gᖴ KO ETNᗩ ᑕHODᗩ ᗷEHEN KE ᒪODE TEᖇI Gᖴ TO ᗰEᖇI ᖇᗩNDI ᗷᗩNGᗩYI ᗩᗷᗷ ᑕHᗩᒪ TEᖇI ᗰᗩᗩKO ᑕHODTᗩ ᖴIᖇSE",
    "HᗩᖇI HᗩᖇI GHᗩᗩS ᗰE ᒍHOᑭDᗩ TEᖇI ᗰᗩᗩKᗩ ᗷHOSDᗩ",
    "ᑕHᗩᒪ TEᖇE ᗷᗩᗩᑭ KO ᗷHEᒍ TEᖇᗩ ᗷᗩSKᗩ NHI HE ᑭᗩᑭᗩ SE ᒪᗩDEGᗩ Tᑌ",
    "TEᖇI ᗷEHEN KI ᑕHᑌTH ᗰE ᗷOᗰᗷ DᗩᒪKE ᑌDᗩ DᑌNGᗩ ᗰᗩᗩKE ᒪᗩᗯDE",
    "TEᖇI ᗰᗩᗩKO TᖇᗩIN ᗰE ᒪEᒍᗩKE TOᑭ ᗷED ᑭE ᒪITᗩKE ᑕHOD DᑌNGᗩ Sᑌᗩᖇ KE ᑭIᒪᒪE",
    "TEᖇI ᗰᗩᗩᗩKE NᑌDES GOOGᒪE ᑭE ᑌᑭᒪOᗩD KᗩᖇDᑌNGᗩ ᗷEHEN KE ᒪᗩEᗯDE",
    "TEᖇI ᗷEHEN KO ᑕHOD ᑕHODKE ᐯIDEO ᗷᗩNᗩKE XNXX.ᑕOᗰ ᑭE NEEᒪᗩᗰ KᗩᖇDᑌNGᗩ KᑌTTE KE ᑭIᒪᒪE",
    "TEᖇI ᗰᗩᗩᗩKI ᑕHᑌDᗩI KO ᑭOᖇNHᑌᗷ.ᑕOᗰ ᑭE ᑌᑭᒪOᗩD KᗩᖇDᑌNGᗩ Sᑌᗩᖇ KE ᑕHODE",
    "ᗩᗷE TEᖇI ᗷEHEN KO ᑕHODᑌ ᖇᗩNDIKE ᗷᗩᑕHHE TEᖇEKO ᑕHᗩKKO SE ᑭIᒪᗯᗩᐯᑌNGᗩ ᖇᗩNDIKE ᗷᗩᑕHHE",
    "TEᖇI ᗰᗩᗩKI ᑕHᑌTH ᖴᗩᗩDKE ᖇᗩKDIᗩ ᗰᗩᗩKE ᒪODE ᒍᗩᗩ ᗩᗷᗷ SIᒪᗯᗩᒪE",
    "TEᖇI ᗷEHEN KI ᑕHᑌTH ᗰE Kᗩᗩᒪᗩ ᒪODᗩᗩᗩ ᗰEᖇᗩᗩᗩ ᖇᗩNDI KE ᗷᗩᒪᗩKK",
    "TEᖇI ᗷEHEN ᒪETI ᗰEᖇI ᒪᑌND ᗷᗩDE ᗰᗩSTI SE TEᖇI ᗷEHEN KO ᗰENE ᑕHOD Dᗩᒪᗩ ᗷOHOT SᗩSTE SE",
    "ᗷETE Tᑌ ᗷᗩᗩᑭ SE ᒪEGᗩ ᑭᗩNGᗩ TEᖇI ᗰᗩᗩᗩ KO ᑕHOD DᑌNGᗩ KᗩᖇKE NᗩNGᗩ",
    "HᗩHᗩHᗩH ᗰEᖇE ᗷETE ᗩGᒪI ᗷᗩᗩᖇ ᗩᑭNI ᗰᗩᗩKO ᒪEKE ᗩᗩYᗩ ᗰᗩTH KᗩT Oᖇ ᗰEᖇE ᗰOTE ᒪᑌND SE ᑕHᑌDᗯᗩYᗩ ᗰᗩTH Kᗩᖇ",
    "ᑕHᗩᒪ ᗷETᗩ TᑌᒍHE ᗰᗩᗩᖴ KIᗩ ᗩᗷᗷ ᗩᑭNI Gᖴ KO ᗷHEᒍ",
    "SHᗩᖇᗩᗰ Kᗩᖇ TEᖇI ᗷEHEN Kᗩ ᗷHOSDᗩ KITNᗩ GᗩᗩᒪIᗩ SᑌNᗯᗩYEGᗩ ᗩᑭNI ᗰᗩᗩᗩ ᗷEHEN KE ᑌᑭEᖇ",
    "ᗩᗷE ᖇᗩNDIKE ᗷᗩᑕHHE ᗩᑌKᗩT NHI HETO ᗩᑭNI ᖇᗩNDI ᗰᗩᗩKO ᒪEKE ᗩᗩYᗩ ᗰᗩTH Kᗩᖇ HᗩHᗩHᗩHᗩ",
    "KIDᘔ ᗰᗩDᗩᖇᑕHOD TEᖇI ᗰᗩᗩKO ᑕHOD ᑕHODKE TEᖇᖇ ᒪIYE ᗷHᗩI DEDIYᗩ",
    "ᒍᑌNGᒪE ᗰE NᗩᑕHTᗩ HE ᗰOᖇE TEᖇI ᗰᗩᗩKI ᑕHᑌDᗩI DEKKE Sᗩᗷ ᗷOᒪTE ONᑕE ᗰOᖇE ONᑕE ᗰOᖇE",
    "GᗩᒪI GᗩᒪI ᗰE ᖇEHTᗩ HE SᗩND TEᖇI ᗰᗩᗩKO ᑕHOD Dᗩᒪᗩ Oᖇ ᗷᗩNᗩ DIᗩ ᖇᗩND",
    "Sᗩᗷ ᗷOᒪTE ᗰᑌᒍHKO ᑭᗩᑭᗩ KYOᑌNKI ᗰENE ᗷᗩNᗩDIᗩ TEᖇI ᗰᗩᗩKO ᑭᖇEGNENT",
    "Sᑌᗩᖇ KE ᑭIᒪᒪE TEᖇI ᗰᗩᗩKI ᑕHᑌTH ᗰE Sᑌᗩᖇ Kᗩ ᒪOᑌDᗩ Oᖇ TEᖇI ᗷEHEN KI ᑕHᑌTH ᗰE ᗰEᖇᗩ ᒪODᗩ",
    "ᑕHᗩᒪ ᑕHᗩᒪ ᗩᑭNI ᗰᗩᗩKI ᑕHᑌᑕHIYᗩ DIKᗩ ᗩᑌᖇ 50$ SEND ᒍᖇ EᗩᗩHᗩ Hᑌ ᗩᑌᖇ 40$ TIᑭ KIDSS TEᖇI ᗰQᗩ KE NᑌDESS ᐯIᖇᗩᒪ KᗩᖇᑌNGᗩ",
    "HᗩHᗩHᗩHᗩ ᗷᗩᑕHHE TEᖇI ᗰᗩᗩᗩKO ᑕHOD DIᗩ NᗩNGᗩ KᗩᖇKE ᑭOᖇNNHᑌD Oᖇ TEᖇI ᗰᗩᗩ KI ᑕHᑌDᗩI KI ᐯIDEO ᑌᑭᒪOᗩD Kᖇ ᖇᗩHᗩ. Hᑌᑌ",
    "TEᖇI ᗰᗩᗩ KO ᑕHEEᗰS SE ᑕHᑌDᗯᗩᐯᑌNGᗩ ᗰᗩDEᖇᑕHOOD KE ᑭIᒪᒪE ᑕHEEᗰS ᗷHI ᑕHOD Kᖇ HᑌI HᑌI KᗩᖇEGᗩ TEᖇI ᗰᗩᗩ ᒍO ITNI SᗩᗩSTI ᖇᗩᗩND HᗩI ",
    "TEᖇI ᗷEHEN KI ᑕHᑌTH ᗰE ᗰᑌTHKE ᖴᗩᖇᗩᖇ HOᒍᗩᐯᑌNGᗩ HᑌI HᑌI HᑌI",
    "SᑭEED ᒪᗩᗩᗩ TEᖇI ᗷEHEN ᑕHODᑌ ᖇᗩNDIKE ᑭIᒪᒪE ᑕHᑌDᗯᗩ Kᖇ TEᖇI ᗷHEN KO ᗷHI ᗷEEᒍ Nᗩ ᑌSKO ᗷHI ᑕHIDNᗩ HᗩII ",
    "ᗩᖇE ᖇE ᗰEᖇE ᗷETE KYOᑌN SᑭEED ᑭᗩKᗩD Nᗩ ᑭᗩᗩᗩ ᖇᗩHᗩ ᗩᑭNE ᗷᗩᗩᑭ Kᗩ HᗩHᗩH",
    "SᑌN SᑌN Sᑌᗩᖇ KE ᑭIᒪᒪE ᒍHᗩNTO KE SOᑌDᗩGᗩᖇ ᗩᑭNI ᗰᑌᗰᗰY KI NᑌDES ᗷHEᒍ",
    "ᗩᗷE SᑌN ᒪODE TEᖇI ᗷEHEN Kᗩ ᗷHOSDᗩ ᖴᗩᗩD DIYᗩ Hᑌ ᒍᗩᗩDᗩ SHOᑕK Nᗩ HIO TEᖇI ᗰᗩᗩ SE ᑭᑌXH ᒪE",
    "TEᖇI ᗰᗩᗩKO KHᑌᒪE ᗷᗩᒍᗩᖇ ᗰE ᑕHOD Dᗩᒪᗩ ᑭᑌNᒍᗩᗷI ᗷHᑌT ᑭᗩTᗩK ᑭᗩTᗩᗩK ᒍᖇ ᑕHODᗩ TEᖇI ᗰᗩᗩ KOO",
    "ᗰEᖇE ᒪᑌND KE ᗷᗩᗩᒪ NE TEᖇI ᗷHEN Kᗩ Dᗩᗩᒪᗩᗩᒪᒪ ᑕHOD ᑕHOD Kᖇ Kᗩᖇᑌ ᑌSKO ᖴIHᗩᗩᒪ",
    "ᗩᑭNI GᗩᗩND ᑕHᗩKKO SE ᑕHᑌDᗯᗩᗩ ᗰE. TOH TEᖇI ᗰᗩᗩ KI GᗩND ᗰE ᗰᑌTH Kᖇ ᗩᗩᖇᗩHᗩ Hᑌᑌ",
    "ᗩᑭNI ᒪᑌND ᑕHOOSᒪEE ᗷEETE TEᖇI YE ᗩᑌKᗩT HᗩI ᗷᗩSS ᗷᗩᒪᗩK. TEᖇI ᗩᑌKᗩT KI ᗰᗩᗩ ᑕHOD ᑕHᑌKᗩ Hᑌ ᗷᗩᗩᑭ ᗷOᒪKᖇ ᖴᗩᗩᖇᗩᖇ HOᒍᗩᗩ ᑕHᗩKEE",
    "TEᖇI ᗰᗩᗩ Kᖇ ᗷHOSDEE Kᗩᗩ ᑭᗩᗩNI NIKᗩᒪ Kᖇ ᑭEᒪᑌᑌᑌᑌ. TEᖇI ᗰᗩᗩ Kᗩ ᗷHOSDᗩ ᒪᗩᗩᒪ HO ᒍᗩYGᗩ ITNᗩ ᑕHODᑌNGᗩ",
    "ᗷHEN KE ᒪᗩᑌDE TEEI ᗷHEN ᗰE KᑌTNE ᒪODE 1,2,5,8,77 ᒪODE HᗩHᗩHᗩ ᑕHᗩKKEE",
    "ᗷHEN KE TᗩKKE TEᖇI ᗰᗩᗩ ᗷHI ᑕHᑌD ᒍᗩYEGI ᒍᗩISE GᗩNGSTEᖇ KI ᗰᗩᗩ ᑕHᑌDI THI",
    "ᗷETE TEᖇI ᗰᗩᗩ KI GᗩND ᗰE ᒪᗩᑭTOᑭ Kᗩ ᑕHᗩᖇGEᖇ ᒪᗩGᗩ Kᖇ TEᖇI ᗰᗩᗩ KI ᑕHᑌTTᗩD ᗷᒪᗩST Kᗩᖇᑌ",
    "ᒪᑌND KE ᗷᗩᗩᗩᒪ ᒍHᗩT KE ᑭISSSᑌᑌ TEᖇI ᗰᗩᗩ KE ᗷHOSDE ᗰE KᑌTTE KI ᒍEEᗷ",
    "KᗩSH OS DIN ᗰᑌTH ᗰᖇKE SOᒍTᗩ ᗰ TᑌN ᑭᗩIDᗩ Nᗩ HOTᗩᗩ",
    "GᗩᒪTI Kᖇ DIYᗩ ᗰE 5 Sᗩᗩᒪ ᑭEHᗩᒪE TEᖇI ᗰᗩᗩ KO ᑕHOD Kᖇᖇ ᑌS DIN ᑕONDOᗰ ᑌSE KᖇᒪETᗩ ᗩᗩᒍ YE NOᗷᗩᗩT NI ᗩᗩTI",
    "GᗩNDᑌ TEᖇI GᗩND KᑌTTE KO DEEE TEᖇI ᗰᗩᗩ KI ᑕHᑌᑌTTᗩD Hᑌᗰ HE ᖴᗩᗩDTE HᗩII",
    "THOᖇI ᗩᗰᗰI KI GᗩᗩND ᗰE ᗷᗩᗰᗷᑌ DEDᑌNGᗩᗩᗩᗩᗩᗩ ᗩᑌᖇ ᑌᑕHKᗩ ᑌᑕKᗩ Kᖇ ᑌSKI ᑕHᑌT ᖴᗩᗩDᑌNGᗩ",
    "ᗷHEN KE ᒪODE ITNᗩ ᗷᗩᗩᗩDᗩ ᖇᗩᗩND HᗩI Tᑌ ᗯᗩᗩH ITNᗩ ᑕHᑌDᗯᗩ ᖇᗩᗩHᗩᗩ",
    "GOTE KITNE ᗷHI ᗷᗩDE HO, ᒪᑌND KE NIᑕHE HI ᖇEHTE HᗩI YE ᗷᗩᗩT EK ᗷᗩNDE NE ᗷOᒪI THI ᗩᗩᒍ ᑭᗩTᗩ ᒪᗩᗩGᗩ ᗯO GOOTᗩ Tᑌ HᗩI",
    "ᗰE ᗩᑌᖇ Tᑌ EK DIN EK KHOTE Oᖇ GᗩᗩYE ᗰE ᑌS SᗩSTI ᖇᗩNDI KO ᗷHᑌT ᑕHODᗩ ᗩᑌᖇ ᗩNDEᖇ SE ᗷHᑌT ᗩᗯᗩᒍ ᗩᗩI ᒍᗩᗷ Tᑌ ᗩNDEᖇ GᗩYᗩ ᗷᗩᗩS EK ᗩᗯᗩᒍ ᗩᗩI OHH ᗰᑌᗰᗰY ᗩᗩᑭ",
    "TEᖇI ᗰᗩ KI KᗩᒪI ᑕHᑌT ᑕHᑌT Kᖇ KITNE ₹ NE NᗩᗰE ᒪIKHᗯᗩYEGᗩ 100¿ 200¿ OK 500₹ᖴINᗩᒪ TEᖇI ᗰᗩᗩ KE NᑌDES SEND Kᖇ ᗰEᖇE NᗩᗰE KE SᗩTH",
    "ᗷHEN KE ᒪIDE TEᖇI ᗰᗩᗩ KI TᗩᗩᖇEH TᑌᒍE ᗷHI KHOOTE ᑭᖇ SᗩSTI ᖇᗩᗩND ᗷᗩNᗩ Kᖇ ᑕHᑌᗯᗩᑌNGᗩ ᑕHᗩᗰᗰᗩᗩᖇ KE HᗩᗩᗩTOO",
    "ᑕHᑌTIYᗩ ᖇᗩᗩND KE SᗩSTII ᖇᗩNDII ᗷEETE TEᖇI ᗰᗩᗩ KE ᗷHOSDE ᗰE ᗰEᖇE ᒪODE ᗰEᖇᗩ ",
    "TEᖇI ᗰᗩᗩ KI ᑕHᑌT ᑭE ᒍᑕᗷ ᑕHᗩDHᗩᗩ DᑌNGᗩ GᗩNDDᑌ SᑌNN Kᖇ ᖴᗩᗩT GᗩI Kᒪ TEᖇI ᗰᗩᗩ KO ᒪᗩᗩNᗩ KᖇKE ᗷᗩTᗩᑌNGᗩ ᖴIᖇ KᗩᒪᗩᑭNᗩ ᗰᗩT TEᖇI ᗰᗩᗩ KI ᖴᗩᗩTI ᑕHᑌD DEKH Kᖇ",
    "TEᖇI ᗷHEN ᗰEᖇE KᑌTTE KO ᖇOᒍ ᗷᒪOᗯ ᒍOᗷ DETI HᗩI TEᖇI ᗷHEN ᗩᑌᖇ ᗰEᖇE KᑌTTE Kᗩ ᗩᖴᖴᗩIᖇ ᑕHᗩᒪ ᖇᗩHᗩ ",
    "TEᖇI Gᖴ K SᗩᗩTH ᗰᗰS ᗷᗩNᗩᗩ ᑕHᑌKᗩ Hᑌ ᑭOᖇN HᑌD ᑭᖇ ᒍᗩᗩ ᗩᑌᖇ TEᖇI Gᖴ Kᗩ NᗰE Dᗩᗩᒪ Kᖇ DEKH ᒪE TEᖇI Gᖴ KI DOGGY STYᒪE ᗰE ᑕHODᗩᗩ",
    "Kᗩᒪᗩᗩ Kᗩᗩᒪᗩᗩ ᒪODᗩᗩᗩ ᗰEᖇᗩᗩ ᒪᗩᗩᒪ ᒪᗩᗩᒪ NIKᗩᒪᑌ KHᑌᑌN TEᖇᗩ ᑕHᗩKKE TEᖇI GᗩND ᖴᗩᗩT GᗩI",
    "TEᖇIIIIII ᗰᗩᗩᗩᗩ KI ᑕHᑌTTT ᗰE ᗩᗷᑕD ᒪIKH DᑌNGᗩ ᗰᗩᗩ KE ᒪODE",
    "TEᖇI ᗰᗩᗩ KO ᒪEKᗩᖇ ᗰᗩI ᖴᗩᖇᗩᖇ HO ᒍᑌNGᗩ ᖴIᖇ 1Y ᗷᗩᗩD TEᖇᗩᗩ EK ᑕᑌTE Sᗩ ᗷHᗩI ᒪEKᖇ ᗩᗩᑌNGᗩ",
    "ᖇᗩNIDIII ᗷᗩᗩᑭ KE ᑕHᗩKKE ᒪᗩDKEE TEᖇI ᗰᗩᗩ KI GᗩND TOH ᗰIᗩ KHᗩᒪIᖴᗩ SE ᗷHI. ᗷᗩDI HᗩI TEᖇI ᗰᗩᗩ TOH HEᗩᐯY ᑭOᖇᖇN STᗩᖇ NIKᒪI",
    "ᗷᗩᑕHEE TEᖇI ᗰᗩᗩ Kᗩ ᖇᗩᑭ HO ᖇᗩHᗩ HᗩI YᗩHᗩ ᑭᖇ ᗩᗩᒍᗩ DEKHᒪEE TEᖇI ᗰᗩIYᗩ KI GᗩND ᗰE 3ᒪOGO KE ᒪODE Dᗩᒪ ᖇHE EK SᗩTH",
    "ᖇᗩNDI KE ᑭIᒪᒪE TEᖇI ᗰᗩᗩ KO ᑌᑕHKᗩᗩ Kᖇ ᑭEᒪ DIYᗩ ISS GᖇOᑌᑭ ᑭᖇ GᗩNDᑌᑌ ᑕHᑌDᗯᗩᒪIYᗩ TY Sᗩᗷ SE EK EK KᖇKE",
    "TEᖇIIIII ᗰᗩᗩᗩ KO ᗷHEᒍᒍᒍ Tᑌ ITNQ ᑕHᑌDᗯᗩ ᒪIYᗩ TEᖇI ᑕHᑌT DHIᒪᒪI HO GᗩI ᗩᗩᗷ TEᖇI ᗰᗩᗩ KI HᗩᖇD ᑭᑌSSY ᖴᗩᗩDᑌNGᗩ",
    "TEᖇᗩᗩ ᗷᗩᗩᗩᗩᑭ Hᑌ ᗰE HᗩHᗩHHᗩ. TEᖇI ᗰᗩᗩ Kᗩ ᗷHOSDᗩ ᖴᗩᗩDᗩᗩT ᗰE",
    "ᗰᗩDᗩᖇᑕHODDD TEᖇI ᗰᗩᗩ KO ᒪᑌND ᖴEEK Kᖇ ᑭᖇEGNENT Kᖇᑌ",
    "TEᖇI ᗰᗩᗩᗩ Kᗩᗩ ᗷHOSDEE ᗰE ᑕOᑕOᒪᗩᗩ ᗩᑌᖇ ᗰENTOS Dᗩᒪ Kᖇ ᑕHODᑌᑌ. ᑕHᗩKKE ᑕHᑌD GᗩYᗩᗩ Tᑌ ᗷHEN KE ᒪODE ᗩᑌKᗩTᒪESS TᗩTTE",
    "NIKᗩᒪ ᗰᗩDᗩᖇᑕHOD ᑕHᑌD GᗩᗩYᗩ Tᑌ ᗷEETEE TEᖇI ᗷHEN KO ᗷEEᒍ ᑌSKO. ᑕHODᑌNGᗩ ᗩᗩᗷ ᗷINᗩ. ᖇᑌKHEE",
    "HIᒍᒍᗩDE TEᖇI ᗰᗩᗩIYᗩᗩ KI GᗩND ᗰE TᑌᒍE ᗯᗩᑭIS Dᗩᗩᒪ Kᖇ Tᗩᑭᗩ Tᗩᑭ ᑕHODᑌNGᗩ ᗷHEN KE ᒪODE TEᖇI ᗰᗩᗩ Kᗩ GᗩNGᗷᗩNG KᗩᖇᗩHᑌ ᗰE 2ᒪOGO KE SᗩTH",
    "ᗩᑌKᗩT HI TEᖇI ᗰEᖇESE ᑕONTᖇO KᖇNE KI ¿ NᗩHI Nᗩ ᗷHEN KE TᗩKKE TEᖇI SᗩSTI ᖇᗩᗩND ᗰᗩᗩ KI ᑕHᑌTTᗩD ᗰE EXTᖇᗩ ᗰIᑕ ᒪᗩGᗩ Kᖇ ᑕHODᑌ",
    "NIᗷᗷᗩ NIᗷᗷI KE 4ᖴEET KE ᑭIᒪEE TEᖇI NIᗷᗷI ᗩᗰᗰᗩ ᗰE SᗩᖇE ᗷᗩNDO KE ᒪODE",
    "ᗰEᖇE HᗩᗩTH ᗰE HᗩI ᗰEᖇᗩ ᒪODᗩ TEᖇI ᗰᗩᗩ KI ᑕHᑌTTᗩD ᑭᑌNᒍᗩᗷI ᖴHOODᗩ",
]
